import React,{useEffect,useState} from 'react';
import {ArrowRight,BookOpen,Check,ClipboardCheck,Download,FileText,Plus,RotateCcw,ShieldCheck,Users,X} from 'lucide-react';
import {demoFileUrl,isPublicDemo} from './publicDemo';
import {AccountFields,blankAccount} from './auth';
import {UploadDialog} from './documents';
import {actionLabels,AdminChange,api,Audit,Badge,Busy,Empty,Governance,Modal,PageHeading,patch,post,Submission,System,time,User,useWorkspace} from './shared';

function useLoad<T>(initial:T,load:()=>Promise<T>){const [data,setData]=useState(initial);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [version,setVersion]=useState(0);const refresh=()=>setVersion(v=>v+1);
  useEffect(()=>{let live=true;setError('');setLoading(true);load().then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[version]);
  return {data,error,loading,refresh};
}
function LoadError({error,onRetry}:{error:string;onRetry:()=>void}){return <div className="load-error" role="alert">{error}<button className="secondary" onClick={onRetry}>重试</button></div>}

export function AdminHome(){
  const {user,libs,navigate}=useWorkspace();const {data,error,loading,refresh}=useLoad<{regs:User[];submissions:Submission[];changes:AdminChange[];audit:Audit[];governance:Governance}|null>(null,async()=>{const [regs,submissions,changes,audit,governance]=await Promise.all([api<User[]>('/registrations'),api<Submission[]>('/submissions'),api<AdminChange[]>('/admin-changes'),api<Audit[]>('/audit'),api<Governance>('/governance')]);return {regs,submissions,changes,audit,governance}});
  const cards=[{title:'员工注册',value:data?.regs.filter(x=>x.review_status==='pending').length||0,path:'/admin/registrations',icon:Users},{title:'资料入库',value:data?.submissions.filter(x=>x.status==='pending').length||0,path:'/admin/submissions',icon:FileText},{title:'管理员变更',value:data?.changes.filter(x=>x.status==='pending').length||0,path:'/admin/governance',icon:ShieldCheck}];
  return <div className="page-content"><PageHeading eyebrow="工作台总览" title={`${user.display_name}，今天的工作从这里开始。`} actions={<button className="secondary" onClick={refresh}><RotateCcw size={16}/>刷新</button>}/>{error&&<LoadError error={error} onRetry={refresh}/>}<section className="admin-welcome"><div><span className="eyebrow">知识有序，工作从容</span><h2>管理团队的共同知识。</h2><p>{libs.length} 个文库 · {libs.reduce((n,l)=>n+l.document_count,0)} 份文档</p></div><button className="primary" onClick={()=>navigate('/admin/libraries')}><BookOpen size={17}/>管理文库<ArrowRight size={16}/></button></section>{data?.governance.needs_completion&&<div className="setup-banner"><div><strong>完成管理员设置</strong><p>添加复核管理账号，并选择治理职责。</p></div><button className="primary" onClick={()=>navigate('/admin/governance')}>继续设置<ArrowRight size={16}/></button></div>}
  <div className="section-title"><h2>待处理</h2></div><div className="task-grid">{cards.map(c=><button className="task-card" key={c.title} onClick={()=>navigate(c.path)}><span className="task-icon"><c.icon size={22}/></span><span>{c.title}</span><strong>{loading?'—':c.value}</strong><small>查看申请<ArrowRight size={14}/></small></button>)}</div><div className="section-title"><h2>最近操作</h2><button className="text-button" onClick={()=>navigate('/admin/audit')}>全部记录<ArrowRight size={15}/></button></div><AuditTable logs={data?.audit.slice(0,6)||[]}/></div>;
}

export function Registrations(){
  const {libs,notify}=useWorkspace();const {data,error,loading,refresh}=useLoad<User[]>([],()=>api('/registrations'));const [filter,setFilter]=useState('pending');const [review,setReview]=useState<User|null>(null);const [approve,setApprove]=useState(true);const [note,setNote]=useState('');const [grants,setGrants]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [failure,setFailure]=useState('');
  const visible=data.filter(u=>filter==='pending'?u.review_status==='pending':u.review_status!=='pending');
  function open(u:User,approved:boolean){setReview(u);setApprove(approved);setNote('');setGrants({});setFailure('')}
  async function submit(e:React.FormEvent){e.preventDefault();if(!review||busy)return;setBusy(true);try{await post('/registrations/'+review.id+'/review',{approve,note,grants:Object.fromEntries(Object.entries(grants).filter(([,p])=>p))});setReview(null);refresh();notify(approve?'员工账号已开通。':'注册申请已驳回。')}catch(e){setFailure((e as Error).message)}finally{setBusy(false)}}
  return <div className="page-content"><PageHeading eyebrow="申请审核" title="员工注册"/><section className="surface"><div className="list-toolbar"><div className="tabs"><button className={filter==='pending'?'active':''} onClick={()=>setFilter('pending')}>待审核<span>{data.filter(u=>u.review_status==='pending').length}</span></button><button className={filter==='processed'?'active':''} onClick={()=>setFilter('processed')}>已处理</button></div><button className="icon-button" aria-label="刷新注册申请" onClick={refresh}><RotateCcw size={17}/></button></div>{error?<LoadError error={error} onRetry={refresh}/>:loading?<div className="loading-inline"><Busy/>正在加载…</div>:visible.length?<div className="table-scroll"><table><thead><tr><th>申请人</th><th>账号</th><th>申请时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{visible.map(u=><tr key={u.id}><td><div className="user-cell"><span className="avatar">{u.display_name[0]}</span><strong>{u.display_name}</strong></div></td><td>{u.username}</td><td className="muted">{time(u.created_at||0)}</td><td><Badge status={u.review_status}/></td><td>{u.review_status==='pending'?<div className="row-buttons"><button className="text-button" onClick={()=>open(u,true)}><Check size={15}/>通过</button><button className="text-button reject" onClick={()=>open(u,false)}>驳回</button></div>:<span className="muted">{u.review_note||'已处理'}</span>}</td></tr>)}</tbody></table></div>:<Empty title={filter==='pending'?'暂无待审核的注册申请':'暂无已处理申请'}/>}</section>{review&&<Modal title={approve?'开通员工账号':'驳回注册申请'} onClose={()=>{if(!busy)setReview(null)}}><form onSubmit={submit}><div className="review-person"><span className="avatar">{review.display_name[0]}</span><div><strong>{review.display_name}</strong><small>{review.username}</small></div></div>{approve&&<div className="grant-list"><h3>开通文库</h3>{libs.length?libs.map(l=><label key={l.id}><span>{l.name}</span><select aria-label={'开通 '+l.name} value={grants[l.id]||''} onChange={e=>setGrants({...grants,[l.id]:e.target.value})}><option value="">暂不开通</option><option value="view">查看</option><option value="submit">查看与提交资料</option></select></label>):<p className="muted">暂无文库，可稍后分配。</p>}</div>}<label>审核备注<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={300} rows={3}/></label>{failure&&<div className="error" role="alert">{failure}</div>}<footer><button className="secondary" type="button" disabled={busy} onClick={()=>setReview(null)}>取消</button><button className={approve?'primary':'danger'} disabled={busy}>{busy?<Busy/>:approve?'确认开通':'确认驳回'}</button></footer></form></Modal>}</div>;
}

export function Contributions({admin=false}:{admin?:boolean}){
  const {notify,refresh:refreshWorkspace,openSource}=useWorkspace();const {data,error,loading,refresh}=useLoad<Submission[]>([],()=>api('/submissions'));const [filter,setFilter]=useState('pending');const [upload,setUpload]=useState(false);const [review,setReview]=useState<Submission|null>(null);const [approve,setApprove]=useState(true);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [failure,setFailure]=useState('');const visible=data.filter(s=>filter==='all'||s.status===filter);
  useEffect(()=>{const t=setInterval(refresh,7000);return()=>clearInterval(t)},[]);
  return <div className="page-content"><PageHeading eyebrow={admin?'申请审核':'个人资料'} title={admin?'资料入库审核':'我的提交'} actions={!admin?<button className="primary" onClick={()=>setUpload(true)}><Plus size={16}/>提交资料</button>:<button className="secondary" onClick={refresh}><RotateCcw size={16}/>刷新</button>}/><section className="surface"><div className="list-toolbar"><div className="tabs">{[['pending','待审核'],['approved','已通过'],['rejected','已驳回'],['all','全部']].map(([v,label])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{label}{v==='pending'&&<span>{data.filter(x=>x.status==='pending').length}</span>}</button>)}</div></div>{error?<LoadError error={error} onRetry={refresh}/>:loading&&!data.length?<div className="loading-inline"><Busy/>正在加载…</div>:visible.length?<div className="table-scroll"><table><thead><tr><th>资料名称</th><th>目标文库</th>{admin&&<th>提交人</th>}<th>提交时间</th><th>状态</th><th>操作 / 备注</th></tr></thead><tbody>{visible.map(s=><tr key={s.id}><td><div className="doc-name"><span className={'file-icon '+s.extension}>{s.extension.toUpperCase()}</span><strong>{s.name}</strong></div></td><td>{s.library_name}</td>{admin&&<td>{s.submitter_name}</td>}<td className="muted">{time(s.created_at)}</td><td><Badge status={s.status}/>{s.status==='approved'&&s.document_status&&<div className="substatus"><Badge status={s.document_status}/></div>}</td><td><div className="row-buttons">{admin&&s.status==='pending'?<><button className="text-button" onClick={()=>{setReview(s);setApprove(true);setNote('');setFailure('')}}>审核通过</button><button className="text-button reject" onClick={()=>{setReview(s);setApprove(false);setNote('');setFailure('')}}>驳回</button></>:s.document_id&&<button className="text-button" onClick={()=>openSource(s.document_id!).catch(e=>notify(e.message))}>查看文档</button>}{s.note&&<small className="review-note">{s.note}</small>}</div></td></tr>)}</tbody></table></div>:<Empty title={filter==='pending'?'暂无待审核资料':'暂无提交记录'} detail={!admin?'你提交的资料与审核进度，会出现在这里。':undefined}/>}</section>
    {upload&&<UploadDialog onClose={()=>setUpload(false)} onDone={refresh}/>}{review&&<Modal title={approve?'审核资料':'驳回资料'} onClose={()=>{if(!busy)setReview(null)}}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await post('/submissions/'+review.id+'/review',{approve,note});setReview(null);refresh();await refreshWorkspace();notify(approve?'审核通过，资料开始处理。':'资料已驳回。')}catch(e){setFailure((e as Error).message)}finally{setBusy(false)}}}><div className="review-document"><FileText size={30}/><div><strong>{review.name}</strong><p>{review.library_name} · {review.submitter_name}</p></div></div><a className="secondary review-download" href={isPublicDemo?demoFileUrl('submissions',review.id):'/api/submissions/'+review.id+'/file'} target="_blank" rel="noreferrer"><Download size={16}/>下载待审原文件</a><label>审核备注<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={300} rows={3}/></label>{failure&&<div className="error" role="alert">{failure}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={()=>setReview(null)}>取消</button><button className={approve?'primary':'danger'} disabled={busy}>{busy?<Busy/>:approve?'通过并入库':'确认驳回'}</button></footer></form></Modal>}</div>;
}

export function UsersPage(){
  const {notify}=useWorkspace();const {data,error,loading,refresh}=useLoad<User[]>([],()=>api('/users'));const [dialog,setDialog]=useState(false);const [account,setAccount]=useState(blankAccount);const [busy,setBusy]=useState(false);const [failure,setFailure]=useState('');const [changing,setChanging]=useState('');
  return <div className="page-content"><PageHeading eyebrow="团队成员" title="成员账号" actions={<button className="primary" onClick={()=>{setAccount(blankAccount());setFailure('');setDialog(true)}}><Plus size={17}/>新建员工</button>}/><section className="surface">{error?<LoadError error={error} onRetry={refresh}/>:loading?<div className="loading-inline"><Busy/>正在加载…</div>:<div className="table-scroll"><table><thead><tr><th>成员</th><th>账号</th><th>身份</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.map(u=><tr key={u.id}><td><div className="user-cell"><span className="avatar">{u.display_name[0]}</span><strong>{u.display_name}</strong></div></td><td>{u.username}</td><td>{u.role==='admin'?'管理员':'员工'}</td><td><Badge status={u.review_status==='approved'?(u.active?'active':'inactive'):u.review_status}/></td><td>{u.role==='employee'&&u.review_status==='approved'&&<button className="text-button" disabled={changing===u.id} onClick={async()=>{setChanging(u.id);try{await patch('/users/'+u.id,{active:!u.active});refresh();notify('账号状态已更新。')}catch(e){notify((e as Error).message)}finally{setChanging('')}}}>{u.active?'停用':'启用'}</button>}</td></tr>)}</tbody></table></div>}</section>{dialog&&<Modal title="新建员工" onClose={()=>{if(!busy)setDialog(false)}}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await post('/users',{...account,role:'employee'});setDialog(false);refresh();notify('员工账号已创建。')}catch(e){setFailure((e as Error).message)}finally{setBusy(false)}}}><AccountFields value={account} onChange={setAccount}/>{failure&&<div className="error">{failure}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={()=>setDialog(false)}>取消</button><button className="primary" disabled={busy}>{busy?<Busy/>:'创建员工'}</button></footer></form></Modal>}</div>;
}

export function MembersPage(){const {libs,notify,refresh:refreshWorkspace}=useWorkspace();const [lid,setLid]=useState(libs[0]?.id||'');const [users,setUsers]=useState<User[]>([]);const [members,setMembers]=useState<{id:string;permission:string}[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [changing,setChanging]=useState('');const [version,setVersion]=useState(0);
  useEffect(()=>{if(!libs.some(l=>l.id===lid))setLid(libs[0]?.id||'')},[libs]);
  useEffect(()=>{let live=true;setUsers([]);setMembers([]);setError('');setLoading(true);if(!lid){setLoading(false);return}Promise.all([api<User[]>('/users'),api<{id:string;permission:string}[]>(`/libraries/${lid}/members`)]).then(([u,m])=>{if(live){setUsers(u.filter(x=>x.role==='employee'&&x.review_status==='approved'));setMembers(m)}}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[lid,version]);
  async function change(uid:string,permission:string){setChanging(uid);try{await api(`/libraries/${lid}/members/${uid}`,{method:permission?'PUT':'DELETE',...(permission?{body:JSON.stringify({permission})}:{})});setMembers(m=>[...m.filter(x=>x.id!==uid),...(permission?[{id:uid,permission}]:[])]);await refreshWorkspace();notify('文库授权已更新。')}catch(e){notify((e as Error).message)}finally{setChanging('')}}
  return <div className="page-content"><PageHeading eyebrow="团队成员" title="文库授权"/><section className="surface"><div className="document-controls"><label className="inline-label">选择文库<select aria-label="授权文库" value={lid} onChange={e=>setLid(e.target.value)}>{libs.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div>{!lid?<Empty title="还没有文库"/>:error?<LoadError error={error} onRetry={()=>setVersion(v=>v+1)}/>:loading?<div className="loading-inline"><Busy/>正在加载…</div>:users.length?<div className="table-scroll"><table><thead><tr><th>员工</th><th>账号状态</th><th>文库权限</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className="user-cell"><span className="avatar">{u.display_name[0]}</span><div><strong>{u.display_name}</strong><small>{u.username}</small></div></div></td><td><Badge status={u.active?'active':'inactive'}/></td><td><select aria-label={u.display_name+'的文库权限'} value={members.find(m=>m.id===u.id)?.permission||''} disabled={!u.active||changing===u.id} onChange={e=>change(u.id,e.target.value)}><option value="">未开通</option><option value="view">查看</option><option value="submit">查看与提交资料</option></select></td></tr>)}</tbody></table></div>:<Empty title="暂无已开通的员工账号"/>}</section></div>;
}

function CompleteSetup({onDone}:{onDone:()=>void}){const {notify}=useWorkspace();const [account,setAccount]=useState(blankAccount);const [duty,setDuty]=useState('initiator');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <section className="surface complete-setup"><h2>完成管理员设置</h2><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await post('/auth/complete-setup',{second_admin:account,current_duty:duty});onDone();notify('管理员设置已完成。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><h3>第二位管理员</h3><AccountFields value={account} onChange={setAccount}/><label>当前账号的治理职责<select value={duty} onChange={e=>setDuty(e.target.value)}><option value="initiator">变更申请</option><option value="reviewer">变更复核</option></select></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?<Busy/>:'完成设置'}</button></form></section>;
}

export function GovernancePage(){const {user,notify}=useWorkspace();const {data,error,loading,refresh}=useLoad<{governance:Governance;users:User[];changes:AdminChange[]}|null>(null,async()=>{const [governance,users,changes]=await Promise.all([api<Governance>('/governance'),api<User[]>('/users'),api<AdminChange[]>('/admin-changes')]);return{governance,users,changes}});
  const [apply,setApply]=useState(false);const [action,setAction]=useState('promote');const [target,setTarget]=useState('');const [initiator,setInitiator]=useState('');const [reviewer,setReviewer]=useState('');const [reason,setReason]=useState('');const [review,setReview]=useState<AdminChange|null>(null);const [approve,setApprove]=useState(true);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [failure,setFailure]=useState('');
  const available=data?.users.filter(u=>u.review_status==='approved'&&(action==='promote'?u.role==='employee'&&u.active:action==='reactivate'?u.role==='admin'&&!u.active:u.role==='admin'&&u.id!==data.governance.initiator_id&&u.id!==data.governance.reviewer_id))||[];
  const admins=data?.users.filter(u=>u.role==='admin'&&u.active&&u.review_status==='approved')||[];
  function start(){setApply(true);setAction('promote');setTarget('');setInitiator(data?.governance.initiator_id||'');setReviewer(data?.governance.reviewer_id||'');setReason('');setFailure('')}
  async function submit(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);try{await post('/admin-changes',{action,target_id:target||available[0]?.id,initiator_id:initiator,reviewer_id:reviewer,reason});setApply(false);refresh();notify('变更申请已提交。')}catch(e){setFailure((e as Error).message)}finally{setBusy(false)}}
  const dutyNames=(id:string|null)=>data?.users.find(u=>u.id===id)?.display_name||'待设置';
  return <div className="page-content"><PageHeading eyebrow="治理工作" title="管理员变更" actions={data?.governance.initiator_id===user.id?<button className="primary" onClick={start}><Plus size={16}/>发起变更</button>:undefined}/>{error?<LoadError error={error} onRetry={refresh}/>:loading?<div className="loading-inline"><Busy/>正在加载…</div>:data?.governance.needs_completion?<CompleteSetup onDone={refresh}/>:<><div className="duty-grid"><section className="surface"><ShieldCheck size={22}/><div><span>变更申请</span><strong>{dutyNames(data?.governance.initiator_id||null)}</strong></div></section><section className="surface"><ClipboardCheck size={22}/><div><span>变更复核</span><strong>{dutyNames(data?.governance.reviewer_id||null)}</strong></div></section></div><section className="surface"><div className="list-toolbar"><h2>变更记录</h2><button className="icon-button" aria-label="刷新变更记录" onClick={refresh}><RotateCcw size={17}/></button></div>{data?.changes.length?<div className="table-scroll"><table><thead><tr><th>变更事项</th><th>申请人 / 复核人</th><th>申请时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{data.changes.map(c=><tr key={c.id}><td><strong>{actionLabels[c.action]}{c.target_name?' · '+c.target_name:''}</strong><small className="table-note">{c.reason}</small>{c.action==='duties'&&<small className="table-note">申请：{dutyNames(JSON.parse(c.payload).initiator_id)} · 复核：{dutyNames(JSON.parse(c.payload).reviewer_id)}</small>}{c.note&&<small className="table-note">{c.note}</small>}</td><td>{c.requester_name} / {c.reviewer_name}</td><td className="muted">{time(c.created_at)}</td><td><Badge status={c.status}/></td><td>{c.status==='pending'&&c.reviewer_id===user.id&&c.requested_by!==user.id&&<div className="row-buttons"><button className="text-button" onClick={()=>{setReview(c);setApprove(true);setNote('');setFailure('')}}>复核通过</button><button className="text-button reject" onClick={()=>{setReview(c);setApprove(false);setNote('');setFailure('')}}>驳回</button></div>}</td></tr>)}</tbody></table></div>:<Empty title="暂无管理员变更记录"/>}</section></>}
    {apply&&<Modal title="发起管理员变更" onClose={()=>{if(!busy)setApply(false)}}><form onSubmit={submit}><label>变更类型<select value={action} onChange={e=>{setAction(e.target.value);setTarget('')}}>{Object.entries(actionLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{action==='duties'?<><label>变更申请账号<select value={initiator} onChange={e=>setInitiator(e.target.value)}>{admins.map(u=><option value={u.id} key={u.id}>{u.display_name} ({u.username})</option>)}</select></label><label>变更复核账号<select value={reviewer} onChange={e=>setReviewer(e.target.value)}>{admins.map(u=><option value={u.id} key={u.id}>{u.display_name} ({u.username})</option>)}</select></label></>:<label>目标账号<select value={target||available[0]?.id||''} onChange={e=>setTarget(e.target.value)} required>{!available.length&&<option value="">暂无符合条件的账号</option>}{available.map(u=><option value={u.id} key={u.id}>{u.display_name} ({u.username})</option>)}</select></label>}<label>变更原因<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={300} required rows={3}/></label>{failure&&<div className="error">{failure}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={()=>setApply(false)}>取消</button><button className="primary" disabled={busy||(action!=='duties'&&!available.length)}>{busy?<Busy/>:'提交申请'}</button></footer></form></Modal>}
    {review&&<Modal title="复核管理员变更" onClose={()=>{if(!busy)setReview(null)}}><form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await post('/admin-changes/'+review.id+'/review',{approve,note});setReview(null);refresh();notify(approve?'管理员变更已生效。':'变更申请已驳回。')}catch(e){setFailure((e as Error).message)}finally{setBusy(false)}}}><h3>{actionLabels[review.action]}{review.target_name?' · '+review.target_name:''}</h3><p>{review.reason}</p>{review.action==='duties'&&<p>申请：{dutyNames(JSON.parse(review.payload).initiator_id)} · 复核：{dutyNames(JSON.parse(review.payload).reviewer_id)}</p>}<label>复核备注<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={300} rows={3}/></label>{failure&&<div className="error" role="alert">{failure}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={()=>setReview(null)}>取消</button><button className={approve?'primary':'danger'} disabled={busy}>{busy?<Busy/>:approve?'确认通过':'确认驳回'}</button></footer></form></Modal>}</div>;
}

const auditLabels:Record<string,string>={setup:'初始化',setup_two_admins:'初始化管理员',complete_admin_setup:'完成管理员设置',create_user:'创建员工',registration_requested:'申请员工账号',registration_approved:'通过注册申请',registration_rejected:'驳回注册申请',user_state:'更新账号状态',create_library:'创建文库',edit_library:'编辑文库',delete_library:'删除文库',grant:'更新文库授权',revoke:'撤销文库授权',upload:'上传文档',delete_document:'删除文档',reindex:'重新处理文档',create_directory:'创建目录',edit_directory:'编辑目录',delete_directory:'删除目录',move_document:'移动文档目录',submission_requested:'提交资料',submission_approved:'通过资料审核',submission_rejected:'驳回资料',admin_change_requested:'申请管理员变更',admin_change_approved:'通过管理员变更',admin_change_rejected:'驳回管理员变更',install_fictional_demo:'导入虚构演示'};
function AuditTable({logs}:{logs:Audit[]}){return <section className="surface">{logs.length?<div className="table-scroll"><table><thead><tr><th>操作</th><th>操作人</th><th>时间</th><th>记录编号</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{auditLabels[l.action]||l.action}</td><td>{l.actor_name||'系统'}</td><td className="muted">{time(l.at)}</td><td className="muted">#{l.id}</td></tr>)}</tbody></table></div>:<Empty title="暂无操作记录"/>}</section>}
export function AuditPage(){const {data,error,loading,refresh}=useLoad<Audit[]>([],()=>api('/audit'));return <div className="page-content"><PageHeading eyebrow="工作记录" title="操作记录" actions={<button className="secondary" onClick={refresh}><RotateCcw size={16}/>刷新</button>}/>{error?<LoadError error={error} onRetry={refresh}/>:loading?<div className="loading-inline"><Busy/>正在加载…</div>:<AuditTable logs={data}/>}</div>}
export function ServicePage(){if(isPublicDemo)return <div className="page-content"><PageHeading eyebrow="公开作品演示" title="服务状态"/><section className="surface service-card"><FileText size={24}/><h2>浏览器证据检索</h2><Badge status="ready"/><p>32 份虚构资料已加载。在线演示使用原文证据摘录，操作保存在当前浏览器。</p><p>AI 生成服务、真实账号认证和六种格式导入可在本地完整版本使用。</p></section></div>;return <LocalServicePage/>}
function LocalServicePage(){const {data,error,loading,refresh}=useLoad<System|null>(null,()=>api('/system'));return <div className="page-content"><PageHeading eyebrow="运行状态" title="服务状态" actions={<button className="secondary" onClick={refresh}><RotateCcw size={16}/>刷新</button>}/>{error?<LoadError error={error} onRetry={refresh}/>:loading?<div className="loading-inline"><Busy/>正在加载…</div>:<><div className="service-grid"><section className="surface service-card"><FileText size={24}/><h2>文档检索</h2><Badge status={data?.embedding==='ready'?'ready':data?.embedding==='loading'?'processing':'model_unavailable'}/>{data?.embedding==='unavailable'&&<p>{data.detail}</p>}</section><section className="surface service-card"><ShieldCheck size={24}/><h2>AI 问答</h2><Badge status={data?.generation_configured?'active':'model_unavailable'}/>{!data?.generation_configured&&<p>问答服务尚未配置，可先使用证据摘录。</p>}</section></div><section className="surface quota-card"><h2>请求额度</h2><div className="quota-items"><div><span>每分钟请求</span><strong>{data?.quota.minute_used||0}<small> / 5</small></strong><progress max={5} value={data?.quota.minute_used||0}/></div><div><span>24 小时请求</span><strong>{data?.quota.day_used||0}<small> / 100</small></strong><progress max={100} value={data?.quota.day_used||0}/></div><div><span>处理中问答</span><strong>{data?.queue_count||0}</strong></div></div></section></>}</div>}
