import React, {useState} from 'react';
import {ArrowRight, BookOpen, FileText, ShieldCheck, Sparkles} from 'lucide-react';
import {Busy, isPublicDemo, Mark, User, post} from './shared';

type Account={username:string;password:string;display_name:string};
export const blankAccount=():Account=>({username:'',password:'',display_name:''});
export function AccountFields({value,onChange,prefix='',newPassword=true}:{value:Account;onChange:(a:Account)=>void;prefix?:string;newPassword?:boolean}){
  if(isPublicDemo)return <><label>{prefix}演示显示名称<input value={value.display_name} onChange={e=>onChange({...value,display_name:e.target.value})} maxLength={40} required/></label><label>{prefix}演示账号<input value={value.username} onChange={e=>onChange({...value,username:e.target.value})} maxLength={40} required/></label></>;
  return <>{newPassword&&<label>{prefix}显示名称<input autoComplete="name" value={value.display_name} onChange={e=>onChange({...value,display_name:e.target.value})} maxLength={40} required/></label>}<label>{prefix}账号<input autoComplete="username" placeholder="至少 3 位英文、数字或下划线" value={value.username} onChange={e=>onChange({...value,username:e.target.value})} pattern="[a-zA-Z0-9_.-]{3,40}" required/></label><label>{prefix}密码<input type="password" autoComplete={newPassword?'new-password':'current-password'} placeholder="至少 10 位" value={value.password} onChange={e=>onChange({...value,password:e.target.value})} minLength={10} maxLength={128} required/></label></>;
}

export function Auth({setup,path,navigate,onLogin}:{setup:boolean;path:string;navigate:(p:string)=>void;onLogin:(u:User,portal:string)=>void}){
  const isAdmin=path.startsWith('/admin');const register=path==='/employee/register';
  const [account,setAccount]=useState(blankAccount);const [second,setSecond]=useState(blankAccount);
  const [step,setStep]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [sent,setSent]=useState(false);
  const entrance=path==='/'&&!setup;
  if(isPublicDemo)return <DemoEntrance onLogin={onLogin}/>;
  async function submit(e:React.FormEvent){e.preventDefault();setError('');if(setup&&step===1){setStep(2);return}setBusy(true);
    try{if(register){await post('/auth/register',account);setSent(true);setAccount(blankAccount())}
      else{const u=await post<User>('/auth/'+(setup?'setup':'login'),setup?{initiator:account,reviewer:second}:{username:account.username,password:account.password,portal:isAdmin?'admin':'employee'});onLogin(u,setup||isAdmin?'admin':'employee')}}
    catch(e){setError((e as Error).message)}finally{setBusy(false)}
  }
  return <div className="auth-page"><section className="auth-story"><a className="brand" href="/" onClick={e=>{e.preventDefault();navigate('/')}}><Mark/><span>知序<small>ZHIXU</small></span></a><div className="auth-copy"><span className="eyebrow">企业知识 · 有序生长</span><h1>把经验留下，<br/>让知识同行。</h1><p>从一份文档，到一次新的发现。<br/>你的团队知识，汇聚于此。</p><div className="auth-art"><div className="art-card"><FileText size={22}/><div><strong>知识文库</strong><span>制度 · 经验 · 项目资料</span></div></div><div className="art-card dark"><Sparkles size={22}/><div><strong>灵感，从一个好问题开始</strong><span>查阅资料，探索答案</span></div></div><div className="art-card"><BookOpen size={22}/><div><strong>常读常新</strong><span>收藏你的每一次发现</span></div></div></div></div><small className="auth-footer">知序 · 企业知识空间</small></section><section className="auth-form"><div className="form-inner"><span className="eyebrow">{setup?'建立知识空间':isAdmin?'管理员工作台':'员工知识门户'}</span><h2>{setup?'开始使用知序':entrance?'欢迎来到知序':sent?'申请已提交':register?'申请员工账号':isAdmin?'管理员登录':'员工登录'}</h2><p>{setup?(step===1?'设置申请管理账号':'设置复核管理账号'):entrance?'选择入口，开启今天的知识之旅。':sent?'审核完成后，你可以从员工入口登录。':register?'填写账号信息，提交开通申请。':'欢迎回来，继续你的工作。'}</p>
    {entrance?<div className="entry-options"><button onClick={()=>navigate('/employee/login')}><BookOpen/><div><strong>员工知识门户</strong><span>查阅文档、收藏与 AI 问答</span></div><ArrowRight size={18}/></button><button onClick={()=>navigate('/admin/login')}><ShieldCheck/><div><strong>管理员工作台</strong><span>管理文库、成员与审核</span></div><ArrowRight size={18}/></button></div>:sent?<button className="primary auth-submit" onClick={()=>navigate('/employee/login')}>返回员工登录<ArrowRight size={18}/></button>:<form onSubmit={submit}>{setup&&<div className="setup-steps"><span className={step===1?'selected':''}>01 申请管理账号</span><span className={step===2?'selected':''}>02 复核管理账号</span></div>}<AccountFields value={setup&&step===2?second:account} onChange={setup&&step===2?setSecond:setAccount} newPassword={setup||register}/>{error&&<div className="error" role="alert">{error}</div>}<div className="auth-buttons">{setup&&step===2&&<button type="button" className="secondary" disabled={busy} onClick={()=>setStep(1)}>上一步</button>}<button className="primary auth-submit" disabled={busy}>{busy?<Busy/>:<>{setup?(step===1?'下一步':'创建知识空间'):register?'提交申请':'登录'}<ArrowRight size={18}/></>}</button></div></form>}
    {!setup&&!entrance&&!sent&&<div className="auth-links">{isAdmin?<button onClick={()=>navigate('/employee/login')}>前往员工登录</button>:<><button onClick={()=>navigate(register?'/employee/login':'/employee/register')}>{register?'已有账号，返回登录':'申请员工账号'}</button><button onClick={()=>navigate('/admin/login')}>管理员入口</button></>}</div>}</div><small>知序 ZHIXU</small></section></div>;
}

function DemoEntrance({onLogin}:{onLogin:(u:User,portal:string)=>void}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function enter(persona:string){setBusy(true);setError('');try{const u=await post<User>('/auth/login',{persona});onLogin(u,u.role==='admin'?'admin':'employee')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="auth-page"><section className="auth-story"><div className="brand"><Mark/><span>知序<small>ZHIXU</small></span></div><div className="auth-copy"><span className="eyebrow">企业知识 · 有序生长</span><h1>把经验留下，<br/>让知识同行。</h1><p>一个可以动手体验的企业知识门户。<br/>32 份虚构资料，7 个文库，6 种文档格式。</p><div className="auth-art"><div className="art-card"><FileText size={22}/><div><strong>星桥科技 · 虚构演示</strong><span>入职 · 财务 · IT · 交付 · 项目</span></div></div><div className="art-card dark"><Sparkles size={22}/><div><strong>从问题找到原文</strong><span>证据摘录与引用位置</span></div></div><div className="art-card"><ShieldCheck size={22}/><div><strong>管理工作台</strong><span>成员授权 · 资料审核 · 变更复核</span></div></div></div></div><small className="auth-footer">知序 · 企业知识空间</small></section><section className="auth-form"><div className="form-inner"><span className="eyebrow">公开作品演示</span><h2>选择一个身份，开始体验。</h2><p>所有公司、人员和业务资料均为虚构。操作保存在当前浏览器，可随时重置。</p><div className="entry-options">{[{id:'employee',name:'员工 · 林舟',description:'查阅文档、收藏、提问与提交资料',icon:BookOpen},{id:'initiator',name:'管理员 · 顾宁',description:'文库管理、入库审核与发起身份变更',icon:ShieldCheck},{id:'reviewer',name:'复核管理员 · 周砚',description:'体验另一位管理员的变更复核',icon:ShieldCheck}].map(x=><button key={x.id} disabled={busy} onClick={()=>enter(x.id)}><x.icon/><div><strong>{x.name}</strong><span>{x.description}</span></div><ArrowRight size={18}/></button>)}</div>{error&&<div className="error" role="alert">{error}</div>}<p className="demo-entry-note">在线版提供浏览器证据摘录。AI 生成问答和六格式文件导入可在本地完整版本使用。</p><a className="text-button" href="https://github.com/lhui278674-ux/zhixu-knowledge" target="_blank" rel="noreferrer">查看项目源码<ArrowRight size={16}/></a></div><small>知序 ZHIXU</small></section></div>;
}
