import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,ChevronRight,ExternalLink,FileText,History,MessageSquare,PanelRightClose,Plus,RotateCcw,Sparkles,X} from 'lucide-react';
import {api,Badge,Busy,isPublicDemo,Citation,Empty,PageHeading,post,Question,terminal,time,useWorkspace} from './shared';

export function Chat({questionId=''}:{questionId?:string}){
  const {user,libs,notify,navigate,openSource}=useWorkspace();
  const [active,setActive]=useState<Question|null>(null);const [input,setInput]=useState('');const [scope,setScope]=useState(isPublicDemo?'__demo__':'');const [mode,setMode]=useState(isPublicDemo?'evidence':'ai');const [busy,setBusy]=useState(false);const [showEvidence,setShowEvidence]=useState(true);const [loadError,setLoadError]=useState('');
  const events=useRef<EventSource|null>(null);const currentId=useRef('');const mounted=useRef(true);const end=useRef<HTMLDivElement>(null);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;events.current?.close()}},[]);
  useEffect(()=>{if(scope&&!(scope==='__demo__'&&libs.some(l=>l.demo))&&!libs.some(l=>l.id===scope))setScope('')},[libs,scope]);
  useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[active?.answer]);
  function watch(q:Question){events.current?.close();currentId.current=q.id;setActive({...q,answer:'',citations:[]});setBusy(true);const es=new EventSource(`/api/qa/questions/${q.id}/events`);events.current=es;
    es.addEventListener('status',e=>{const d=JSON.parse((e as MessageEvent).data);setActive(a=>a?{...a,status:d.status}:a)});
    es.addEventListener('citations',e=>{const d=JSON.parse((e as MessageEvent).data);setActive(a=>a?{...a,citations:d.citations}:a)});
    es.addEventListener('delta',e=>{const d=JSON.parse((e as MessageEvent).data);setActive(a=>a?{...a,answer:a.answer+d.text}:a)});
    es.addEventListener('reset',e=>{const d=JSON.parse((e as MessageEvent).data);setActive(a=>a?{...a,answer:d.answer,citations:[]}:a)});
    const finish=()=>{es.close();if(mounted.current){setBusy(false);api<Question>(`/qa/questions/${q.id}`).then(r=>{if(mounted.current&&currentId.current===q.id)setActive(r)}).catch(e=>notify(e.message))}};
    es.addEventListener('done',finish);
    es.onerror=()=>{api<Question>(`/qa/questions/${q.id}`).then(latest=>{if(terminal.includes(latest.status)){es.close();if(mounted.current&&currentId.current===q.id){setActive(latest);setBusy(false)}}}).catch(()=>{es.close();if(mounted.current){setBusy(false);setLoadError('会话已过期或服务不可用，请重新登录。')}})};
  }
  useEffect(()=>{let live=true;setLoadError('');if(!questionId){events.current?.close();currentId.current='';setActive(null);setBusy(false);return}
    if(currentId.current!==questionId){events.current?.close();setActive(null);setBusy(true);api<Question>('/qa/questions/'+questionId).then(q=>{if(!live)return;setScope(JSON.parse(q.library_ids)?.[0]||'');setMode(q.mode);if(terminal.includes(q.status)){currentId.current=q.id;setActive(q);setBusy(false)}else watch(q)}).catch(e=>{if(live){setLoadError(e.message);setBusy(false)}})}
    const timer=setInterval(()=>api<Question>('/qa/questions/'+questionId).then(q=>{if(live&&terminal.includes(q.status)){setActive(q);setBusy(false)}}).catch(e=>{if(live){setActive(null);setLoadError(e.message);setBusy(false)}}),6000);
    return()=>{live=false;clearInterval(timer)};
  },[questionId]);
  async function ask(text=input){if(!text.trim()||busy)return;setBusy(true);setLoadError('');try{const r=await post<{id:string}>('/qa/questions',{question:text,library_ids:scope==='__demo__'?libs.filter(l=>l.demo).map(l=>l.id):scope?[scope]:[],mode});setInput('');const q=await api<Question>('/qa/questions/'+r.id);if(terminal.includes(q.status)){currentId.current=q.id;setActive(q);setBusy(false)}else watch(q);navigate('/employee/chat?question='+r.id)}catch(e){setBusy(false);setInput(text);notify((e as Error).message)}}
  const open=(c:Citation)=>openSource(c.document_id,c.chunk_id).catch(e=>notify(e.message));
  const answerText=active?.answer.replace(/^本地证据摘录（未调用生成模型）：/,'证据摘录：').replace(/^根据已授权资料，以下原文直接提供依据：/,'以下原文提供依据：')||'';
  return <div className={'chat-layout '+(!showEvidence?'no-evidence':'')}><section className="chat-main"><div className="chat-toolbar"><div><MessageSquare size={18}/><strong>问问知序</strong></div><select aria-label="问答文库范围" value={scope} onChange={e=>setScope(e.target.value)}><option value="">企业文库（不含演示）</option>{libs.some(l=>l.demo)&&<option value="__demo__">虚构演示文库（全部）</option>}{libs.map(l=><option key={l.id} value={l.id}>{l.name}{l.demo?'（演示）':''}</option>)}</select><button className="icon-button" aria-label={showEvidence?'收起来源面板':'展开来源面板'} onClick={()=>setShowEvidence(v=>!v)}><PanelRightClose size={19}/></button></div>
  {loadError?<div className="load-error" role="alert">{loadError}<button className="secondary" onClick={()=>navigate('/employee/chat')}>新建问答</button></div>:!active?<div className="welcome"><div className="welcome-icon"><Sparkles size={30}/></div><span className="eyebrow">知识，从好问题开始</span><h1>今天，有什么想了解的？</h1><p>查找制度细节，回顾项目经验。<br/>仅回答本企业业务、已授权资料和本系统使用问题。</p>{!libs.length?<Empty title="还没有可用资料" detail="联系管理员开通文库后，即可提问。"/>:<><div className="suggestion-heading">{libs.some(l=>l.demo)?'试试这些问题 · 虚构演示':'试着从这里开始'}</div><div className="suggestions">{(libs.some(l=>l.demo)?['新员工如何领取办公设备？','请假需要提前多久申请？','星舟项目的交付节点是什么？','出差住宿上限是多少？']:['入职需要准备哪些资料？','项目有哪些交付节点？','差旅报销需要什么凭证？','如何申请办公设备？']).map(s=><button key={s} onClick={()=>{if(libs.some(l=>l.demo))setScope('__demo__');setInput(s)}}><FileText size={17}/><span>{s}</span><ArrowRight size={15}/></button>)}</div></>}</div>:<div className="conversation"><div className="question-line"><span className="avatar small">{user.display_name.slice(0,1)}</span><div><span className="message-meta">你 · {time(active.created_at)}</span><h2>{active.question}</h2></div></div><div className="answer-line"><span className="answer-avatar"><Sparkles size={19}/></span><div className="answer-body"><div className="answer-head"><strong>知序</strong><span>{active.mode==='evidence'?'证据摘录':'AI 问答'}</span><Badge status={active.status}/></div>{active.answer?<div className="answer-text">{answerText.split(/(\[S\d+\])/).map((s,i)=>/^\[S\d+\]$/.test(s)?<button className="inline-cite" key={i} onClick={()=>{const c=active.citations.find(c=>'['+c.source_id+']'===s);if(c)open(c)}}>{s}</button>:<React.Fragment key={i}>{s}</React.Fragment>)}</div>:<div className="working"><Busy/>{busy?'正在查找答案…':'正在加载回答…'}</div>}{active.citations.length>0&&<div className="answer-sources"><span><FileText size={14}/>{active.citations.length} 条来源</span><button className="text-button" onClick={()=>setShowEvidence(true)}>查看来源<ArrowRight size={14}/></button></div>}{!busy&&<button className="text-button retry" onClick={()=>setInput(active.question)}><RotateCcw size={14}/>再次提问</button>}<div ref={end}/></div></div></div>}
  <div className="composer-wrap"><form className="composer" onSubmit={e=>{e.preventDefault();ask()}}><textarea aria-label="输入问题" value={input} onChange={e=>setInput(e.target.value)} maxLength={1000} placeholder="输入你的问题…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask()}}}/><div className="composer-bottom"><select aria-label="回答方式" value={mode} onChange={e=>setMode(e.target.value)}>{!isPublicDemo&&<option value="ai">AI 问答</option>}<option value="evidence">证据摘录</option></select>{busy?<button type="button" className="send stop" aria-label="取消处理" disabled={!active} onClick={()=>active&&post('/qa/questions/'+active.id+'/cancel').catch(e=>notify(e.message))}><X size={18}/></button>:<button className="send" aria-label="发送问题" disabled={!input.trim()||!libs.length}><ArrowRight size={20}/></button>}</div></form><div className="composer-note">Enter 发送 · Shift + Enter 换行 <button onClick={()=>navigate('/employee/history')}><History size={13}/>问答历史</button></div></div></section>
  {showEvidence&&<aside className="evidence-panel"><div className="evidence-heading"><strong><FileText size={17}/>引用来源</strong><span>{active?.citations.length||0}</span></div>{active?.citations.length?<div className="citations">{active.citations.map(c=><button className="citation-card" key={c.chunk_id} onClick={()=>open(c)}><div className="citation-top"><span className="cite-no">{c.source_id}</span><span>{c.library_name}</span><ExternalLink size={14}/></div><strong>{c.name}</strong><p>{c.quote||c.text}</p><div className="citation-bottom"><FileText size={13}/>{c.locator.label}<ChevronRight size={14}/></div></button>)}</div>:<Empty title="这里会展示引用文档" detail="提问后，点击来源查看原文位置。"/>}</aside>}</div>;
}

export function QuestionHistory(){const {navigate,notify}=useWorkspace();const [questions,setQuestions]=useState<Question[]>([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState('');const [error,setError]=useState('');
  useEffect(()=>{let live=true;api<Question[]>('/qa/questions').then(q=>{if(live)setQuestions(q)}).catch(e=>{if(live)setError(e.message);notify(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
  return <div className="page-content"><PageHeading eyebrow="个人记录" title="问答历史" actions={<button className="primary" onClick={()=>navigate('/employee/chat')}><Plus size={17}/>新建问答</button>}/><section className="surface"><div className="document-controls"><label className="search-input"><History size={17}/><input aria-label="搜索历史问题" placeholder="搜索历史问题" value={filter} onChange={e=>setFilter(e.target.value)}/></label><span className="result-count">{questions.length} 条问答</span></div>{error?<div className="load-error">{error}</div>:loading?<div className="loading-inline"><Busy/>正在加载…</div>:questions.filter(q=>q.question.includes(filter)).length?<div className="history-list">{questions.filter(q=>q.question.includes(filter)).map(q=><button key={q.id} onClick={()=>navigate('/employee/chat?question='+q.id)}><span className="history-icon"><MessageSquare size={20}/></span><div><strong>{q.question}</strong><small>{time(q.created_at)} · {q.mode==='ai'?'AI 问答':'证据摘录'}</small></div><Badge status={q.status}/><ChevronRight size={18}/></button>)}</div>:<Empty title={filter?'没有匹配的问题':'还没有问答记录'} detail="从一个问题开始，记录会保存在这里。"/>}</section></div>;
}
