import React, {useEffect,useState} from 'react';
import {ArrowRight, BookOpen, ChevronDown, ChevronRight, FileText, Folder, FolderOpen, Pencil, Plus, RotateCcw, Search, Star, Trash2, Upload, X} from 'lucide-react';
import {api,Badge,Busy,isPublicDemo,date,Directory,Doc,Empty,fileAccept,FolderOptions,Highlight,Library,libraryUrl,Modal,PageHeading,patch,post,size,useWorkspace} from './shared';

export function LibraryCards({libs,admin=false,onEdit}:{libs:Library[];admin?:boolean;onEdit?:(l:Library)=>void}){
  const {navigate}=useWorkspace();return <div className="library-grid">{libs.map((l,i)=><article className={'library-card tint-'+i%3} key={l.id}><button className="library-card-link" onClick={()=>navigate(libraryUrl(l.id,admin))}><span className="library-icon"><BookOpen size={25}/></span><span className="library-card-title"><strong>{l.name}</strong>{l.demo===1&&<span className="demo-tag">虚构演示</span>}</span><p>{(l.demo&&l.description==='仅供权限隔离测试，不含真实企业机密'?'星舟研发计划、里程碑与内部项目资料，全部为虚构样例':l.description)||'暂无文库简介'}</p><span className="library-card-meta"><FileText size={14}/>{l.document_count} 份文档 <ArrowRight size={16}/></span></button>{onEdit&&<button className="library-edit icon-button" aria-label={'编辑 '+l.name} onClick={()=>onEdit(l)}><Pencil size={16}/></button>}</article>)}</div>;
}

export function PortalHome(){
  const {user,libs,navigate,notify,openSource}=useWorkspace();const [recent,setRecent]=useState<Doc[]>([]);const [query,setQuery]=useState('');
  useEffect(()=>{let live=true;api<{results:Doc[]}>('/portal/documents?view=recent&limit=6').then(r=>{if(live)setRecent(r.results)}).catch(e=>notify(e.message));return()=>{live=false}},[libs]);
  const ordered=[...libs].sort((a,b)=>recent.filter(d=>d.library_id===b.id).length-recent.filter(d=>d.library_id===a.id).length);
  return <div className="page-content"><section className="portal-hero"><div><span className="eyebrow">你的团队知识空间</span><h1>{user.display_name}，欢迎回来。</h1><p>找到所需资料，也发现新的答案。</p><form className="hero-search" onSubmit={e=>{e.preventDefault();navigate('/employee/documents?q='+encodeURIComponent(query))}}><Search size={20}/><input aria-label="搜索文档标题或正文" placeholder="搜索文档标题或正文…" value={query} onChange={e=>setQuery(e.target.value)} maxLength={200}/><button className="primary">搜索</button></form><div className="hero-actions"><button onClick={()=>navigate('/employee/chat')}><span><SparklesIcon/></span>问问知序<ArrowRight size={16}/></button><button onClick={()=>navigate('/employee/favorites')}><Star size={16}/>我的收藏</button></div></div><div className="hero-decoration" aria-hidden="true"><span className="book b1"/><span className="book b2"/><span className="book b3"/><span className="book-base"/></div></section>
  <div className="section-title"><h2>常用文库 <span>{libs.length}</span></h2><button className="text-button" onClick={()=>navigate('/employee/documents')}>全部文库<ArrowRight size={15}/></button></div>{libs.length?<LibraryCards libs={ordered.slice(0,6)}/>:<Empty title="暂无可访问的文库" detail="联系管理员开通文库后，即可开始查阅。"/>}
  <div className="section-title"><h2>最近查看</h2><button className="text-button" onClick={()=>navigate('/employee/recent')}>查看全部<ArrowRight size={15}/></button></div><section className="surface">{recent.length?<div className="recent-doc-grid">{recent.map(d=><button key={d.id} onClick={()=>openSource(d.id).catch(e=>notify(e.message))}><span className={'file-icon '+d.extension}>{d.extension.toUpperCase()}</span><div><strong>{d.name}</strong><small>{d.library_name} · {date(d.viewed_at||d.created_at)}</small></div><ChevronRight size={16}/></button>)}</div>:<Empty title="还没有阅读记录" detail="打开一份文档，从这里继续上次的阅读。" action={<button className="secondary" onClick={()=>navigate('/employee/documents')}>浏览文档<ArrowRight size={16}/></button>}/>}</section></div>;
}
function SparklesIcon(){return <svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="m12 3 2.6 6.4L21 12l-6.4 2.6L12 21l-2.6-6.4L3 12l6.4-2.6Z"/></svg>}

export function UploadDialog({admin=false,initialLibrary='',initialDirectory='',onClose,onDone}:{admin?:boolean;initialLibrary?:string;initialDirectory?:string;onClose:()=>void;onDone:()=>void}){
  const {libs,notify,refresh}=useWorkspace();const available=admin?libs:libs.filter(l=>l.permission==='submit');
  const [lid,setLid]=useState(initialLibrary||available[0]?.id||'');const [fid,setFid]=useState(initialDirectory);const [dirs,setDirs]=useState<Directory[]>([]);const [files,setFiles]=useState<File[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{setDirs([]);let live=true;if(lid)api<Directory[]>(`/libraries/${lid}/directories`).then(d=>{if(live)setDirs(d)}).catch(e=>setError(e.message));return()=>{live=false}},[lid]);
  async function submit(e:React.FormEvent){e.preventDefault();if(busy||!files.length||!lid)return;setBusy(true);setError('');let completed=0;
    try{for(const file of files){const form=new FormData();form.append('file',file);if(fid)form.append('directory_id',fid);const r=await api<{message?:string;duplicate:boolean}>(`/libraries/${lid}/`+(admin?'documents':'submissions'),{method:'POST',body:form});completed++;if(r.duplicate)notify(r.message||'已跳过重复文档。')}
      notify(admin?`${completed} 份文件已上传。`:`${completed} 份资料已提交，等待审核。`);await refresh();onDone();onClose()}
    catch(e){setFiles(f=>f.slice(completed));setError((e as Error).message)}finally{setBusy(false)}
  }
  return <Modal title={admin?'上传文档':'提交资料'} onClose={()=>{if(!busy)onClose()}}><form onSubmit={submit}>{available.length?<><label>目标文库<select aria-label="目标文库" value={lid} onChange={e=>{setLid(e.target.value);setFid('')}}>{available.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>存放目录<select value={fid} onChange={e=>setFid(e.target.value)}><FolderOptions directories={dirs}/></select></label><label className="dropzone"><Upload size={28}/><strong>{files.length?`已选择 ${files.length} 份文件`:'选择要上传的文件'}</strong><span>{isPublicDemo?'TXT、MD · 在线演示每份不超过 1 MB':'PDF、DOCX、XLSX、PPTX、TXT、MD · 每份不超过 25 MB'}</span><input aria-label="选择上传文件" type="file" accept={isPublicDemo?'.txt,.md':fileAccept} multiple disabled={busy} onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.map((f,i)=><div className="upload-file" key={f.name+i}><FileText size={17}/><span>{f.name}</span><small>{size(f.size)}</small></div>)}</>:<Empty title="暂无可提交的文库" detail="请联系管理员开通资料提交。"/>}{error&&<div className="error" role="alert">{error}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={onClose}>取消</button><button className="primary" disabled={busy||!files.length||!lid}>{busy?<Busy/>:<Upload size={16}/>}{admin?'上传文档':'提交审核'}</button></footer></form></Modal>;
}

export function DocumentCenter({params,view='all',admin=false}:{params:URLSearchParams;view?:'all'|'favorites'|'recent';admin?:boolean}){
  const {libs,notify,navigate,refresh,openSource}=useWorkspace();const lid=params.get('library')||'';const selectedFolder=params.get('directory')||'';const urlQ=params.get('q')||'';const lib=libs.find(l=>l.id===lid);
  const [docs,setDocs]=useState<Doc[]>([]);const [total,setTotal]=useState(0);const [dirs,setDirs]=useState<Directory[]>([]);const [search,setSearch]=useState(urlQ);const [query,setQuery]=useState(urlQ);const [field,setField]=useState('all');const [extension,setExtension]=useState('');const [offset,setOffset]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [revision,setRevision]=useState(0);const [collapsed,setCollapsed]=useState<Set<string>>(new Set());const [upload,setUpload]=useState(false);const [libraryDialog,setLibraryDialog]=useState<Library|'new'|null>(null);const [folderDialog,setFolderDialog]=useState<{id?:string;name:string;parent_id:string|null}|null>(null);const [move,setMove]=useState<Doc|null>(null);const [moveId,setMoveId]=useState('');const [moveDirs,setMoveDirs]=useState<Directory[]>([]);const [confirm,setConfirm]=useState<{title:string;message:string;run:()=>Promise<unknown>}|null>(null);const [saving,setSaving]=useState(false);const [dialogError,setDialogError]=useState('');
  const reload=()=>{setRevision(r=>r+1);refresh().catch(e=>notify(e.message))};
  useEffect(()=>{setSearch(urlQ);setQuery(urlQ);setOffset(0)},[urlQ,lid,selectedFolder,view]);
  useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setOffset(0)},300);return()=>clearTimeout(timer)},[search]);
  useEffect(()=>{let live=true;setDocs([]);setDirs([]);setError('');setLoading(true);
    const queryString=new URLSearchParams({view,q:query,field,offset:String(offset),limit:'30'});if(lid)queryString.set('library_id',lid);if(selectedFolder)queryString.set('directory_id',selectedFolder);if(extension)queryString.set('extension',extension);
    async function load(){try{const [result,folders]=await Promise.all([api<{results:Doc[];total:number}>('/portal/documents?'+queryString),lid?api<Directory[]>(`/libraries/${lid}/directories`):Promise.resolve([])]);if(live){setDocs(result.results);setTotal(result.total);setDirs(folders);setError('')}}catch(e){if(live){setDocs([]);setTotal(0);setError((e as Error).message)}}finally{if(live)setLoading(false)}}
    load();const timer=setInterval(load,5000);return()=>{live=false;clearInterval(timer)};
  },[lid,selectedFolder,view,query,field,extension,offset,revision,libs]);
  useEffect(()=>{setMoveDirs([]);if(!move)return;let live=true;api<Directory[]>(`/libraries/${move.library_id}/directories`).then(d=>{if(live)setMoveDirs(d)}).catch(e=>setDialogError(e.message));return()=>{live=false}},[move?.id]);
  function folderPath(fid=''){const p=new URLSearchParams();if(lid)p.set('library',lid);if(fid)p.set('directory',fid);if(query)p.set('q',query);navigate((admin?'/admin/libraries':'/employee/documents')+'?'+p)}
  async function toggleFavorite(d:Doc){try{await api('/favorites/'+d.id,{method:d.favorite?'DELETE':'PUT'});setDocs(a=>a.map(x=>x.id===d.id?{...x,favorite:d.favorite?0:1}:x));if(view==='favorites')reload();notify(d.favorite?'已取消收藏。':'已加入收藏。')}catch(e){notify((e as Error).message)}}
  async function doMutation(work:()=>Promise<unknown>,done:()=>void){if(saving)return;setSaving(true);setDialogError('');try{await work();done();reload()}catch(e){setDialogError((e as Error).message)}finally{setSaving(false)}}
  function tree(parent:string|null,depth=0):React.ReactNode{return dirs.filter(f=>f.parent_id===parent).map(f=><div key={f.id}><div className={'tree-row '+(selectedFolder===f.id?'chosen':'')} style={{paddingLeft:12+depth*16}}>{dirs.some(x=>x.parent_id===f.id)?<button aria-label={(collapsed.has(f.id)?'展开 ':'收起 ')+f.name} className="tree-chevron" onClick={()=>setCollapsed(s=>{const n=new Set(s);n.has(f.id)?n.delete(f.id):n.add(f.id);return n})}>{collapsed.has(f.id)?<ChevronRight size={14}/>:<ChevronDown size={14}/>}</button>:<span className="tree-chevron"/>}<button className="tree-name" onClick={()=>folderPath(f.id)}><Folder size={16}/><span>{f.name}</span><small>{f.document_count}</small></button>{admin&&<button className="tree-edit" aria-label={'编辑目录 '+f.name} onClick={()=>{setFolderDialog(f);setDialogError('')}}><Pencil size={13}/></button>}</div>{!collapsed.has(f.id)&&tree(f.id,depth+1)}</div>)}
  const title=view==='favorites'?'我的收藏':view==='recent'?'最近查看':lib?lib.name:admin?'文库管理':'全部文档';
  return <div className="page-content"><PageHeading eyebrow={admin?'知识资产':'文档中心'} title={title} description={(lib?.demo&&lib.description==='仅供权限隔离测试，不含真实企业机密'?'星舟研发计划、里程碑与内部项目资料，全部为虚构样例':lib?.description)|| (view==='favorites'?'保存常读的资料，随时回来看看。':view==='recent'?'继续你的阅读与探索。':undefined)} actions={<>{admin&&<button className="secondary" onClick={()=>{setLibraryDialog('new');setDialogError('')}}><Plus size={16}/>新建文库</button>}{(admin?!!lib:libs.some(l=>l.permission==='submit'))&&<button className="primary" onClick={()=>setUpload(true)}><Upload size={16}/>{admin?'上传文档':'提交资料'}</button>}</>}/>
    {view==='all'&&!lid&&<><div className="section-title"><h2>{admin?'知识文库':'文库分类'}</h2><span>{libs.length} 个文库</span></div><LibraryCards libs={libs} admin={admin} onEdit={admin?l=>{setLibraryDialog(l);setDialogError('')}:undefined}/></>}
    {lid&&<div className="library-breadcrumb"><button onClick={()=>navigate(admin?'/admin/libraries':'/employee/documents')}>全部文库</button><ChevronRight size={14}/><button onClick={()=>folderPath()}>{lib?.name||'文库'}</button>{selectedFolder&&<><ChevronRight size={14}/><strong>{dirs.find(f=>f.id===selectedFolder)?.name||'目录'}</strong></>}{admin&&lib&&<button className="text-button" onClick={()=>{setLibraryDialog(lib);setDialogError('')}}><Pencil size={14}/>编辑文库</button>}</div>}
    <div className={'document-layout '+(lid?'has-tree':'')}>
    {lid&&<aside className="directory-panel"><header><strong>文库目录</strong>{admin&&<button className="icon-button" aria-label="新建目录" onClick={()=>{setFolderDialog({name:'',parent_id:selectedFolder||null});setDialogError('')}}><Plus size={17}/></button>}</header><button className={'tree-root '+(!selectedFolder?'chosen':'')} onClick={()=>folderPath()}><FolderOpen size={17}/>全部文档</button>{tree(null)}{!dirs.length&&<p className="directory-empty">暂无目录</p>}{admin&&<button className="text-button tree-add" onClick={()=>{setFolderDialog({name:'',parent_id:selectedFolder||null});setDialogError('')}}><Plus size={14}/>新建目录</button>}</aside>}
    <section className="surface document-surface"><div className="document-controls"><label className="search-input"><Search size={17}/><input aria-label="搜索标题或正文" placeholder="搜索标题或正文" value={search} onChange={e=>setSearch(e.target.value)} maxLength={200}/>{search&&<button aria-label="清除搜索" onClick={()=>setSearch('')}><X size={14}/></button>}</label><select aria-label="搜索字段" value={field} onChange={e=>{setField(e.target.value);setOffset(0)}}><option value="all">标题与正文</option><option value="title">仅标题</option><option value="content">仅正文</option></select><select aria-label="文件格式" value={extension} onChange={e=>{setExtension(e.target.value);setOffset(0)}}><option value="">全部格式</option>{['pdf','docx','xlsx','pptx','txt','md'].map(x=><option value={x} key={x}>{x.toUpperCase()}</option>)}</select><span className="result-count">{total} 份文档</span></div>
    {error?<div className="load-error" role="alert">{error}<button className="secondary" onClick={reload}>重试</button></div>:loading?<div className="loading-inline"><Busy/>正在加载文档…</div>:docs.length?<div className="table-scroll"><table><thead><tr><th className="favorite-col">收藏</th><th>文档名称</th><th>{lid?'目录':'所在文库'}</th><th>状态</th><th>{view==='recent'?'查看时间':'更新时间'}</th>{admin&&<th>操作</th>}</tr></thead><tbody>{docs.map(d=><tr key={d.id}><td><button className={'icon-button favorite '+(d.favorite?'selected':'')} aria-label={(d.favorite?'取消收藏 ':'收藏 ')+d.name} aria-pressed={!!d.favorite} onClick={()=>toggleFavorite(d)}><Star size={17} fill={d.favorite?'currentColor':'none'}/></button></td><td><div className="doc-name"><span className={'file-icon '+d.extension}>{d.extension.toUpperCase()}</span><div><button onClick={()=>openSource(d.id,d.chunk_id||undefined).catch(e=>notify(e.message))}><Highlight text={d.name} query={query}/></button><small>{size(d.size)}{d.locator?' · '+d.locator.label:''}{d.detail&&d.status!=='ready'?' · '+d.detail:''}</small>{d.snippet&&<p className="search-snippet"><Highlight text={d.snippet} query={query}/></p>}</div></div></td><td className="muted">{lid?(d.directory_name||'根目录'):d.library_name}</td><td><Badge status={d.status}/></td><td className="muted">{date(view==='recent'?(d.viewed_at||d.created_at):d.created_at)}</td>{admin&&<td><div className="row-actions"><button className="icon-button" aria-label={'移动 '+d.name} title="移动目录" onClick={()=>{setMove(d);setMoveId(d.directory_id||'');setDialogError('')}}><Folder size={16}/></button><button className="icon-button" aria-label={'重新索引 '+d.name} title="重新处理" onClick={()=>post(`/documents/${d.id}/reindex`).then(()=>{reload();notify('文档已进入处理队列。')}).catch(e=>notify(e.message))}><RotateCcw size={16}/></button><button className="icon-button" aria-label={'删除 '+d.name} onClick={()=>{setDialogError('');setConfirm({title:'删除文档',message:`确认删除「${d.name}」？文件和索引将一并移除。`,run:()=>api(`/documents/${d.id}`,{method:'DELETE'})})}}><Trash2 size={16}/></button></div></td>}</tr>)}</tbody></table></div>:<Empty title={query?'没有找到匹配的文档':view==='favorites'?'还没有收藏':view==='recent'?'还没有阅读记录':'这里还没有文档'} detail={query?'试试其他关键词或调整筛选条件。':view==='favorites'?'点击文档旁的星标，将它加入收藏。':undefined}/>}
    {total>30&&<div className="pagination"><span>{offset+1}–{Math.min(offset+30,total)} / {total}</span><button className="secondary" disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-30))}>上一页</button><button className="secondary" disabled={offset+30>=total} onClick={()=>setOffset(n=>n+30)}>下一页</button></div>}</section></div>
    {admin&&!lid&&<div className="demo-banner"><div><span className="demo-tag">虚构演示</span><strong>用一组示例资料，探索知序。</strong><p>人事、差旅、IT 与项目资料，包含六种文件格式。</p></div><button className="secondary" disabled={saving} onClick={()=>doMutation(()=>post<{message:string}>('/demo').then(r=>notify(r.message)),()=>{})}>{saving?<Busy/>:<BookOpen size={16}/>}导入虚构演示</button></div>}
    {upload&&<UploadDialog admin={admin} initialLibrary={lid} initialDirectory={selectedFolder} onClose={()=>setUpload(false)} onDone={reload}/>}
    {libraryDialog&&<LibraryDialog library={libraryDialog} onClose={()=>setLibraryDialog(null)} onSaved={id=>{setLibraryDialog(null);reload();navigate(libraryUrl(id,true))}} onDelete={l=>{setLibraryDialog(null);setDialogError('');setConfirm({title:'删除文库',message:`确认删除「${l.name}」及其中的目录、文件和提交记录？`,run:()=>api(`/libraries/${l.id}`,{method:'DELETE'}).then(()=>navigate('/admin/libraries'))})}}/>}
    {folderDialog&&<Modal title={folderDialog.id?'编辑目录':'新建目录'} onClose={()=>{if(!saving)setFolderDialog(null)}}><form onSubmit={e=>{e.preventDefault();doMutation(()=>folderDialog.id?patch('/directories/'+folderDialog.id,folderDialog):post(`/libraries/${lid}/directories`,folderDialog),()=>{setFolderDialog(null);notify('目录已保存。')})}}><label>目录名称<input autoFocus value={folderDialog.name} required maxLength={60} onChange={e=>setFolderDialog({...folderDialog,name:e.target.value})}/></label><label>上级目录<select value={folderDialog.parent_id||''} onChange={e=>setFolderDialog({...folderDialog,parent_id:e.target.value||null})}><FolderOptions directories={dirs.filter(d=>d.id!==folderDialog.id)}/></select></label>{dialogError&&<div className="error">{dialogError}</div>}<footer>{folderDialog.id&&<button type="button" className="danger ghost" onClick={()=>{const f=folderDialog;setFolderDialog(null);setDialogError('');setConfirm({title:'删除目录',message:`删除「${f.name}」及其子目录？目录中的文档将保留在文库根目录。`,run:()=>api('/directories/'+f.id,{method:'DELETE'}).then(()=>folderPath())})}}>删除目录</button>}<button type="button" className="secondary" disabled={saving} onClick={()=>setFolderDialog(null)}>取消</button><button className="primary" disabled={saving}>{saving?<Busy/>:'保存目录'}</button></footer></form></Modal>}
    {move&&<Modal title="移动文档" onClose={()=>{if(!saving)setMove(null)}}><form onSubmit={e=>{e.preventDefault();doMutation(()=>patch('/documents/'+move.id,{directory_id:moveId||null}),()=>{setMove(null);notify('文档目录已更新。')})}}><p>{move.name}</p><label>目标目录<select value={moveId} onChange={e=>setMoveId(e.target.value)}><FolderOptions directories={moveDirs}/></select></label>{dialogError&&<div className="error">{dialogError}</div>}<footer><button type="button" className="secondary" disabled={saving} onClick={()=>setMove(null)}>取消</button><button className="primary" disabled={saving}>移动文档</button></footer></form></Modal>}
    {confirm&&<Modal title={confirm.title} onClose={()=>{if(!saving)setConfirm(null)}}><p>{confirm.message}</p>{dialogError&&<div className="error" role="alert">{dialogError}</div>}<footer><button className="secondary" disabled={saving} onClick={()=>setConfirm(null)}>取消</button><button className="danger" disabled={saving} onClick={()=>doMutation(confirm.run,()=>{setConfirm(null);notify('已删除。')})}>{saving?<Busy/>:'确认删除'}</button></footer></Modal>}</div>;
}

function LibraryDialog({library,onClose,onSaved,onDelete}:{library:Library|'new';onClose:()=>void;onSaved:(id:string)=>void;onDelete:(l:Library)=>void}){
  const [name,setName]=useState(library==='new'?'':library.name);const [description,setDescription]=useState(library==='new'?'':library.description);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <Modal title={library==='new'?'新建文库':'编辑文库'} onClose={()=>{if(!busy)onClose()}}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{if(library==='new'){const r=await post<{id:string}>('/libraries',{name,description});onSaved(r.id)}else{await patch('/libraries/'+library.id,{name,description});onSaved(library.id)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>文库名称<input autoFocus value={name} onChange={e=>setName(e.target.value)} maxLength={60} required/></label><label>简介<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={300} rows={3}/></label>{error&&<div className="error">{error}</div>}<footer>{library!=='new'&&<button type="button" className="danger ghost" disabled={busy} onClick={()=>onDelete(library)}>删除文库</button>}<button className="secondary" type="button" disabled={busy} onClick={onClose}>取消</button><button className="primary" disabled={busy}>{busy?<Busy/>:'保存文库'}</button></footer></form></Modal>;
}
